/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with this
 * work for additional information regarding copyright ownership. The ASF
 * licenses this file to You under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

package org.apache.hugegraph.unit.util;

import java.io.BufferedReader;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.StringWriter;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;

import org.junit.Test;

import org.apache.hugegraph.unit.BaseUnitTest;
import org.apache.hugegraph.util.LongEncoding;
import org.apache.hugegraph.testutil.Assert;

/**
 * Replays the golden fixture corpus against {@link LongEncoding}.
 *
 * The corpus locks down the current encode/decode behavior as a
 * compatibility contract: exact output strings, exact decoded values
 * including the intentional wrapping arithmetic around Long.MIN_VALUE,
 * accepted non-canonical inputs, and the exception class raised for each
 * rejected input. Any alternative implementation of this encoding has to
 * reproduce this corpus line by line.
 *
 * The corpus file is generated by {@link LongEncodingGoldenGenerator} and
 * must not be edited by hand.
 */
public class LongEncodingGoldenTest extends BaseUnitTest {

    private static final String CORPUS = "/longencoding-golden.txt";
    private static final int MIN_CASES = 3000;
    private static final int MAX_REPORTED_MISMATCHES = 20;

    @Test
    public void testReplayGoldenCorpus() throws IOException {
        List<String> mismatches = new ArrayList<>();
        int cases = 0;
        int lineNumber = 0;

        InputStream stream = getClass().getResourceAsStream(CORPUS);
        Assert.assertNotNull("Missing corpus resource " + CORPUS, stream);
        try (BufferedReader reader = new BufferedReader(new InputStreamReader(stream, StandardCharsets.US_ASCII))) {
            for (String line; (line = reader.readLine()) != null;) {
                lineNumber++;
                if (line.isEmpty() || line.charAt(0) == '#') {
                    continue;
                }
                cases++;
                String failure = replay(line);
                if (failure != null && mismatches.size() < MAX_REPORTED_MISMATCHES) {
                    mismatches.add("line " + lineNumber + ": " + failure);
                }
            }
        }

        Assert.assertTrue("Corpus suspiciously small: " + cases + " cases", cases >= MIN_CASES);
        Assert.assertTrue(cases + " cases, mismatches:\n" + String.join("\n", mismatches), mismatches.isEmpty());
    }

    /**
     * The replay above checks the implementation against the corpus; this
     * checks the committed corpus against the generator, so the two can't
     * drift apart: editing the generator without regenerating the resource
     * (or hand-editing the resource) fails here.
     */
    @Test
    public void testCorpusMatchesGenerator() throws IOException {
        StringWriter generated = new StringWriter();
        LongEncodingGoldenGenerator.generate(generated);

        InputStream stream = getClass().getResourceAsStream(CORPUS);
        Assert.assertNotNull("Missing corpus resource " + CORPUS, stream);
        ByteArrayOutputStream committed = new ByteArrayOutputStream();
        try {
            byte[] buffer = new byte[8192];
            for (int read; (read = stream.read(buffer)) != -1;) {
                committed.write(buffer, 0, read);
            }
        } finally {
            stream.close();
        }

        Assert.assertEquals("Committed corpus differs from generator " + "output, regenerate " + CORPUS,
                            generated.toString(),
                            new String(committed.toByteArray(), StandardCharsets.US_ASCII));
    }

    private static String replay(String line) {
        String[] fields = line.split("\t", -1);
        if (fields.length != 3) {
            return "malformed line: " + line;
        }
        String method = fields[0];
        String arg = fields[1];
        String expected = fields[2];

        String actual;
        try {
            actual = "ok:" + invoke(method, arg);
        } catch (RuntimeException e) {
            actual = "throw:" + e.getClass().getSimpleName();
        }
        if (actual.equals(expected)) {
            return null;
        }
        return method + "(" + arg + ") expected " + expected + " but was " + actual;
    }

    private static String invoke(String method, String arg) {
        switch (method) {
            case "encodeSortable":
                return LongEncodingGoldenGenerator.escape(LongEncoding.encodeSortable(Long.parseLong(arg)));
            case "encodeSignedB64":
                return LongEncodingGoldenGenerator.escape(LongEncoding.encodeSignedB64(Long.parseLong(arg)));
            case "encodeB64":
                return LongEncodingGoldenGenerator.escape(LongEncoding.encodeB64(Long.parseLong(arg)));
            case "decodeSortable":
                return String.valueOf(LongEncoding.decodeSortable(stringArg(arg)));
            case "decodeSignedB64":
                return String.valueOf(LongEncoding.decodeSignedB64(stringArg(arg)));
            case "decodeB64":
                return String.valueOf(LongEncoding.decodeB64(stringArg(arg)));
            default:
                throw new IllegalArgumentException("Unknown method: " + method);
        }
    }

    private static String stringArg(String arg) {
        return "\\N".equals(arg) ? null : LongEncodingGoldenGenerator.unescape(arg);
    }
}
